name: CI2 Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

env:
  APP_NAME: my-node-appola
  APP_VERSION: latest

jobs:

  # -------------------------
  # Cache + Install
  # -------------------------
  create_cache:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20.19
        uses: actions/setup-node@v4
        with:
          node-version: 20.19
          cache: yarn

      - name: Install Yarn Classic
        run: npm install -g yarn@1

      - name: Install dependencies
        run: yarn install --ignore-engines

  # -------------------------
  # Yarn Tests
  # -------------------------
  yarn_test:
    runs-on: self-hosted
    needs: create_cache
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20.19
        uses: actions/setup-node@v4
        with:
          node-version: 20.19
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test